### ISSUE TITLE
how to load SSPNet dataset？

### ISSUE THREAD

**Issue by LeiiY** [smartcameras/ConflictNET#4]
Just move the dataset as the following？ 
-SSPNet Conflict Corpus（folder contains   videodata.zip，audiodata.zip ，......）
-README.md
-conflict_net.py	
-dataLoad.py	
-gui.py	
-requirements.txt

**Comment by vandana-rajan** [comment]
Hi,

You have to first download the data set using the link given in the readme file. In this code, we used only the audio data. You have to split the audio data into training, validation and test according to the paper given below. 

_Schuller, Björn, et al. "The INTERSPEECH 2013 computational paralinguistics challenge: Social signals, conflict, emotion, autism." Proceedings INTERSPEECH 2013, 14th Annual Conference of the International Speech Communication Association, Lyon, France. 2013._

In the 'dataLoad.py' file, change lines 10,11 and 12 according to your train, val and test paths.
